# Docs: https://jhugman.github.io/uniffi-bindgen-react-native/reference/config-yaml.html

rust:
  repo: https://github.com/Ficik/moonlight-common-rust.git
  branch: dc89fbe8cad4ae717f17f6beb167a928d8c2dddb
  manifestPath: bindings/Cargo.toml

web:
  entrypoint: web/uniffi/entry.ts
  tsBindings: web/uniffi
  defaultFeatures: false
  features: ["web"]
  manifestPatchFile: ./Cargo.wasm.toml
