# Docs: https://jhugman.github.io/uniffi-bindgen-react-native/reference/config-yaml.html

rust:
  repo: https://github.com/Ficik/moonlight-common-rust.git
  branch: 144bfaa731c8e28dc7803feda6b4e40cf360649c
  manifestPath: bindings/Cargo.toml

web:
  entrypoint: web/uniffi/entry.ts
  tsBindings: web/uniffi
  defaultFeatures: false
  features: ["web"]
  manifestPatchFile: ./Cargo.wasm.toml
